build:gcclatest:
  image: gcc:latest
  stage: build
  script:
    - g++ src/helloworld.cpp -o helloWorld
  artifacts:
    paths:
      - helloWorld

test:gcclatest:
  image: gcc:latest
  script:
    - ./helloWorld
  dependencies:
    - build:gcclatest
