.build: &build
  stage: build
  script:
    - g++ src/helloworld.cpp -o helloWorld
  artifacts:
    paths:
      - helloWorld

.test: &test
  stage: test
  script:
    - ./helloWorld

build:gcc:latest:
  image: gcc:latest
  <<: *build

build:gcc:8:
  image: gcc:8
  <<: *build
  
test:gcc:latest:
  image: gcc:latest
  <<: *test
  dependencies:
    - build:gcc:latest

test:gcc:8:
  image: gcc:8
  <<: *test
  dependencies:
    - build:gcc:8
